# Generated by Django 3.2.10 on 2022-03-31 14:36

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='', max_length=64)),
                ('file', models.FileField(upload_to=main.models.user_directory_path)),
                ('status', models.CharField(default='not started', max_length=20)),
                ('percentage_completed', models.IntegerField(default=0)),
                ('unique_key', models.CharField(default=main.models.create_unique_id, max_length=255)),
                ('time_uploaded', models.DateTimeField(default=datetime.datetime.now)),
                ('plain_text', models.TextField(default='')),
                ('subtitle', models.TextField(default='')),
            ],
        ),
    ]
