# Generated by Django 3.2.10 on 2021-12-28 11:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.user_directory_path)),
                ('session_key', models.CharField(max_length=1024)),
                ('moment_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
