# Generated by Django 3.2.10 on 2021-12-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
