# Generated by Django 3.2.10 on 2022-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fileupload_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='data',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
