# Generated by Django 3.2.10 on 2022-01-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fileupload_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='data',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
